apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: pg-op-cluster
  namespace: default
spec:
  teamId: "inspiration-particle"
  numberOfInstances: 1

  postgresql:
    version: "15"
    parameters:
      shared_preload_libraries: "pg_cron"
      cron.database_name: "utro"

  patroni:
    pg_hba:
      # local (unix socket)
      - "local   all             postgres                                md5"
      - "local   all             utro_user                               md5"
      - "local   all             n8n_user                                md5"
      - "local   all             mattermost_user                         md5"

      # ANY host, no-SSL explicitly allowed (matches: no encryption)
      - "hostnossl all           postgres         0.0.0.0/0              md5"
      - "hostnossl all           utro_user        0.0.0.0/0              md5"
      - "hostnossl all           n8n_user         0.0.0.0/0              md5"
      - "hostnossl all           mattermost_user  0.0.0.0/0              md5"
      - "hostnossl all           postgres         ::/0                   md5"
      - "hostnossl all           utro_user        ::/0                   md5"
      - "hostnossl all           n8n_user         ::/0                   md5"
      - "hostnossl all           mattermost_user  ::/0                   md5"

      # ANY host, SSL also allowed
      - "hostssl all            postgres         0.0.0.0/0              md5"
      - "hostssl all            utro_user        0.0.0.0/0              md5"
      - "hostssl all            n8n_user         0.0.0.0/0              md5"
      - "hostssl all            mattermost_user  0.0.0.0/0              md5"
      - "hostssl all            postgres         ::/0                   md5"
      - "hostssl all            utro_user        ::/0                   md5"
      - "hostssl all            n8n_user         ::/0                   md5"
      - "hostssl all            mattermost_user  ::/0                   md5"

  env:
    - name: WAL_S3_BUCKET
      value: utro-a253e7cf-backups
    - name: AWS_REGION
      value: eu-central-1
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: postgres-backup-aws-creds
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: postgres-backup-aws-creds
          key: AWS_SECRET_ACCESS_KEY

  volume:
    size: 40Gi

  enableLogicalBackup: true

  users:
    n8n_user: [CREATEROLE]
    utro_user: [CREATEROLE]
    mattermost_user: [CREATEROLE]

  databases:
    n8n: n8n_user
    utro: utro_user
    mattermost: mattermost_user
