apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: pg-op-cluster
  namespace: default
spec:
  teamId: "inspiration-particle"
  numberOfInstances: 1

  postgresql:
    version: "15"
    parameters:
      shared_preload_libraries: "pg_cron"
      cron.database_name: "utro"

  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          # local (unix socket) access
          - "local   all             postgres                                md5"
          - "local   all             utro_user                               md5"
          - "local   all             n8n_user                                md5"

          # allow access from ANY host (IPv4 + IPv6)
          - "host    all             postgres         0.0.0.0/0              md5"
          - "host    all             utro_user        0.0.0.0/0              md5"
          - "host    all             n8n_user         0.0.0.0/0              md5"
          - "host    all             postgres         ::/0                   md5"
          - "host    all             utro_user        ::/0                   md5"
          - "host    all             n8n_user         ::/0                   md5"

  volume:
    size: 40Gi

  users:
    n8n_user: [CREATEROLE]
    utro_user: [CREATEROLE]

  databases:
    n8n: n8n_user
    utro: utro_user