apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: pg-op-cluster
  namespace: default
spec:
  teamId: "inspiration-particle"
  numberOfInstances: 1

  postgresql:
    version: "15"
    parameters:
      shared_preload_libraries: "pg_cron"
      cron.database_name: "utro"

  # Allow all pods in the cluster (by Pod CIDR)
  patroni:
    pg_hba:
      # SSL connections from pods
      - "hostssl all all 10.42.0.0/16 md5"
      # Non-SSL connections from pods (fixes: 'no encryption')
      - "hostnossl all all 10.42.0.0/16 md5"

  volume:
    size: 40Gi

  users:
    n8n_user: [CREATEROLE]
    utro_user: [CREATEROLE]

  databases:
    n8n: n8n_user
    utro: utro_user