apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: pg-op-cluster
  namespace: default
spec:
  teamId: "inspiration-particle"
  numberOfInstances: 1

  postgresql:
    version: "15"
    parameters:
      shared_preload_libraries: "pg_cron"
      cron.database_name: "utro"

  patroni:
    pg_hba:
      # local (unix socket)
      - "local   all             postgres                                md5"
      - "local   all             utro_user                               md5"
      - "local   all             n8n_user                                md5"

      # ANY host, no-SSL explicitly allowed (matches: no encryption)
      - "hostnossl all           postgres         0.0.0.0/0              md5"
      - "hostnossl all           utro_user        0.0.0.0/0              md5"
      - "hostnossl all           n8n_user         0.0.0.0/0              md5"
      - "hostnossl all           postgres         ::/0                   md5"
      - "hostnossl all           utro_user        ::/0                   md5"
      - "hostnossl all           n8n_user         ::/0                   md5"

      # ANY host, SSL also allowed
      - "hostssl all            postgres         0.0.0.0/0              md5"
      - "hostssl all            utro_user        0.0.0.0/0              md5"
      - "hostssl all            n8n_user         0.0.0.0/0              md5"
      - "hostssl all            postgres         ::/0                   md5"
      - "hostssl all            utro_user        ::/0                   md5"
      - "hostssl all            n8n_user         ::/0                   md5"

  volume:
    size: 40Gi

  users:
    n8n_user: [CREATEROLE]
    utro_user: [CREATEROLE]

  databases:
    n8n: n8n_user
    utro: utro_user