apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-cluster-password-drift
  namespace: default
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: password-drift-check
              image: postgres:17.5
              imagePullPolicy: IfNotPresent
              env:
                - name: DB_HOST
                  value: db-cluster-rw.default.svc.cluster.local
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  value: postgres
                - name: SUPERUSER_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: db-cluster-superuser
                      key: username
                - name: SUPERUSER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: db-cluster-superuser
                      key: password
                - name: OWNER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: psql-owner-password
                      key: password
              command:
                - /bin/sh
                - -c
                - |
                  set -eu
                  if PGPASSWORD="$OWNER_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U owner -d "$DB_NAME" -tAc "select 1" >/dev/null 2>&1; then
                    echo "owner login ok"
                  else
                    echo "owner login failed"
                  fi
                  if ! PGPASSWORD="$SUPERUSER_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$SUPERUSER_USERNAME" -d "$DB_NAME" -tAc "select 1" >/dev/null 2>&1; then
                    echo "superuser login failed; cannot fix drift" >&2
                    exit 1
                  fi
                  PGPASSWORD="$SUPERUSER_PASSWORD" psql -v ON_ERROR_STOP=1 -h "$DB_HOST" -p "$DB_PORT" -U "$SUPERUSER_USERNAME" -d "$DB_NAME" \
                    -v owner_pw="$OWNER_PASSWORD" -v super_pw="$SUPERUSER_PASSWORD" -v super_user="$SUPERUSER_USERNAME" \
                    -c "ALTER ROLE owner WITH LOGIN PASSWORD :'owner_pw'; ALTER ROLE :\"super_user\" WITH LOGIN PASSWORD :'super_pw';"
                  echo "password drift check complete"
