apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-pgpass
  namespace: default
stringData:
  .pgpass: |
    # Format: hostname:port:database:username:password
    # db-cluster owner user
    db-cluster-rw.default.svc.cluster.local:5432:*:owner:${OWNER_PASSWORD}
    # db-cluster postgres superuser  
    db-cluster-rw.default.svc.cluster.local:5432:*:postgres:${POSTGRES_PASSWORD}
