apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-db-user
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: n8n-db-user
    creationPolicy: Owner
    template:
      data:
        username: n8n
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: psql-owner-password
        version: latest
