# Backup bucket for the kadis workloads.
#
# Deliberately separate from utro's utro-a253e7cf-backups: separate bucket,
# separate IAM user, separate credentials, so a misbehaving backup job here
# cannot reach utro's data and retention can be set independently.
#
# The random-looking suffix is fixed at authoring time rather than generated by
# the module, so the bucket name is known before the first apply and can be
# written into the Kubernetes manifests that use it.

module "s3_backup" {
  source = "../modules/s3-backup"

  name_prefix       = "kadis"
  bucket_name       = "kadis-ad77fef6-backups"
  enable_versioning = true
  tags              = var.tags

  # Static access keys rather than IRSA: this is k3s, there is no OIDC provider
  # for AWS to federate with. The keys land in Secret Manager (gcp-secrets.tf)
  # and reach the cluster through External Secrets.
  create_user = true

  create_role       = false
  oidc_provider_arn = ""
  sa_name           = ""
  sa_namespace      = ""

  # Retention for the hourly Płatnik SQL Server backups. Versioning is on, so
  # noncurrent_version_days is what actually reclaims the space when an object
  # is expired or overwritten — without it, "deleted" backups linger forever.
  #
  # The prefix must track the database name in backup-cronjob.yaml. It is a
  # literal string match, so "sqlserver/platnik/" does NOT cover
  # "sqlserver/platnik_migracja/" — the trailing slash stops it. Changing the
  # database without changing this here means the new backups match no rule at
  # all and accumulate forever, silently and at cost.
  #
  # sqlserver/migracja/ is deliberately uncovered: it holds the migration
  # source and the pre-migration backup, which must not expire.
  lifecycle_rules = [
    {
      id                              = "platnik-backups"
      prefix                          = "sqlserver/platnik_migracja/"
      expiration_days                 = 14
      noncurrent_version_days         = 7
      abort_incomplete_multipart_days = 7
    },
    # Nextcloud, and NOTE THE MISSING expiration_days — its absence is the whole
    # point of this rule, not an oversight.
    #
    # This prefix holds a restic repository, not independent dumps. restic
    # deduplicates by content, so one pack file is referenced by however many
    # snapshots happen to contain those bytes, and nothing in the object's age
    # or key says which. Expiring by age would delete data that current
    # snapshots still point at — and restic would not notice until somebody
    # tried to restore, which is the worst possible moment to find out.
    #
    # So retention here is `restic forget --prune`, in
    # clusters/may-chang/nextcloud/backup-cronjob.yaml, which is the only thing
    # that can know what is still referenced. That deliberately contradicts the
    # note above about retention belonging in S3 rather than in the job: that
    # reasoning is right for the Płatnik .bak files, where every object stands
    # alone, and wrong for a deduplicating repository.
    #
    # The rule still exists because an uncovered prefix gets no lifecycle at
    # all, and incomplete multipart uploads would then accumulate billed and
    # invisible. noncurrent_version_days cleans up after restic's own deletes,
    # since the bucket is versioned.
    {
      id                              = "nextcloud-restic"
      prefix                          = "nextcloud/"
      noncurrent_version_days         = 7
      abort_incomplete_multipart_days = 7
    }
  ]
}
