# Backup bucket for the kadis workloads.
#
# Deliberately separate from utro's utro-a253e7cf-backups: separate bucket,
# separate IAM user, separate credentials, so a misbehaving backup job here
# cannot reach utro's data and retention can be set independently.
#
# The random-looking suffix is fixed at authoring time rather than generated by
# the module, so the bucket name is known before the first apply and can be
# written into the Kubernetes manifests that use it.

module "s3_backup" {
  source = "../modules/s3-backup"

  name_prefix       = "kadis"
  bucket_name       = "kadis-ad77fef6-backups"
  enable_versioning = true
  tags              = var.tags

  # Static access keys rather than IRSA: this is k3s, there is no OIDC provider
  # for AWS to federate with. The keys land in Secret Manager (gcp-secrets.tf)
  # and reach the cluster through External Secrets.
  create_user = true

  create_role       = false
  oidc_provider_arn = ""
  sa_name           = ""
  sa_namespace      = ""

  # Retention for the hourly Płatnik SQL Server backups. Versioning is on, so
  # noncurrent_version_days is what actually reclaims the space when an object
  # is expired or overwritten — without it, "deleted" backups linger forever.
  lifecycle_rules = [
    {
      id                              = "platnik-backups"
      prefix                          = "sqlserver/platnik/"
      expiration_days                 = 14
      noncurrent_version_days         = 7
      abort_incomplete_multipart_days = 7
    }
  ]
}
