---
apiVersion: v1
kind: Service
metadata:
  name: open-seo
  namespace: open-seo
  labels:
    app: open-seo
    component: service
spec:
  type: ClusterIP
  selector:
    app: open-seo
    component: deployment
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
