apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-statefulset.yaml
  - gateway-service.yaml
  - core-statefulset.yaml
  - core-service.yaml
  - core-migrate-job.yaml
  - core-event-statefulset.yaml
  - core-event-migrate-job.yaml
  - ui-statefulset.yaml
  - ui-service.yaml
  - utro-cloudflare-tunnel-secret.yaml
  - utro-ingress.yaml
  - utro-cloudflare-statefulset.yaml
  - payment-statefulset.yaml
  - payment-service.yaml
  - payment-migrate-job.yaml
  - notification-statefulset.yaml
  - notification-service.yaml
  - notification-migrate-job.yaml
