apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ui
  namespace: default
  labels:
    app: ui
spec:
  serviceName: ui
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: docker.io/inspirationparticleltd/utro-ui:v0.0.2 # {"$imagepolicy": "flux-system:utro-ui"}
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
