apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: default
  labels:
    app: ui
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ui
