apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: utro-ui
  namespace: default
  labels:
    app: utro-ui
spec:
  serviceName: utro-ui
  replicas: 1
  selector:
    matchLabels:
      app: utro-ui
  template:
    metadata:
      labels:
        app: utro-ui
    spec:
      containers:
      - name: ui
        image: docker.io/inspirationparticleltd/utro-ui:v0.0.7 # {"$imagepolicy": "flux-system:utro-ui"}
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: BFF_URL
          value: "http://utro-gateway.default.svc.cluster.local:9999"
        - name: PORT
          value: "3000"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
