apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: utro-assets-s3-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets
  target:
    name: utro-assets-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: STORAGE_ACCESS_KEY
      remoteRef:
        key: utro-assets-prod-s3-access-key-id
        version: latest
    - secretKey: STORAGE_SECRET_KEY
      remoteRef:
        key: utro-assets-prod-s3-secret-access-key
        version: latest
