apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kadis-contact
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kadis-contact
  filterTags:
    pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    extract: '$0'
  policy:
    semver:
      range: '>=0.0.0'
