apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kadis-turnstile-secret
  namespace: kadis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets
  target:
    name: kadis-turnstile-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        value: "{{ .value | trim }}"
  data:
    - secretKey: value
      remoteRef:
        key: kadis-turnstile-secret
        version: latest
