apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pg-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: openebs
      namespace: flux-system
    - name: external-secrets-resources
      namespace: flux-system
  interval: 10m
  path: ./clusters/home-pc/pg-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
