apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://kps-kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "30s"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki.observability.svc.cluster.local:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: traceID
          matcherRegex: "trace_id=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: tempo
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo.observability.svc.cluster.local:3100
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags:
          - key: service.name
            value: service_name
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
