apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: google-secrets
spec:
  provider:
    gcpsm:
      projectID: danb-ubuntu-k0s
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-creds
            key: key.json
