apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: psql-owner-password
   namespace: default
spec:
   refreshInterval: 1h
   secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
   target:
    name: psql-owner-password
    creationPolicy: Owner
   data:
     - secretKey: value
       remoteRef:
         key: psql-owner-password
         version: latest
