apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-cluster.yaml
  - core-migrate-job.yaml
  - core-statefulset.yaml
  - core-service.yaml
  - payment-migrate-job.yaml
  - payment-statefulset.yaml
  - payment-service.yaml
  - gateway-statefulset.yaml
  - gateway-service.yaml
