apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: utr-staging-notification
  namespace: default
  labels:
    app: utr-staging-notification
spec:
  serviceName: utr-staging-notification
  replicas: 1
  selector:
    matchLabels:
      app: utr-staging-notification
  template:
    metadata:
      labels:
        app: utr-staging-notification
    spec:
      containers:
      - name: notification
        image: ghcr.io/inspiration-particle/utro-notification:0.1.35 # {"$imagepolicy": "flux-system:utr-staging-notification"}
        ports:
        - containerPort: 9002
          name: api
        - containerPort: 18007
          name: health
        env:
        - name: TIMEZONE
          value: "Europe/Warsaw"
        - name: HEALTH_PORT
          value: "18007"
        - name: API_PORT
          value: "9002"
        - name: LOG_LEVEL
          value: "debug"
        - name: SERVICE_NAME
          value: "rpg.notification"
        - name: SERVICE_ENV
          value: "staging"
        - name: ENABLE_DEV_API
          value: "true"
        - name: TR_ENABLED
          value: "true"
        - name: TR_ENDPOINT
          value: "otel-collector.observability.svc.cluster.local:4318"
        - name: TR_HTTPS
          value: "false"
        - name: DB_TRACE
          value: "true"
        - name: DB_SSL
          value: "true"
        - name: DB_NAME
          value: "utr_staging"
        - name: DB_HOST
          value: "pg-staging-cluster.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: utr-staging-user.pg-staging-cluster.credentials.postgresql.acid.zalan.do
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: utr-staging-user.pg-staging-cluster.credentials.postgresql.acid.zalan.do
              key: password
        livenessProbe:
          httpGet:
            path: /live
            port: health
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 60
          periodSeconds: 5
