apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mattermost-filestore-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets
  target:
    name: mattermost-filestore-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: accesskey
      remoteRef:
        key: mattermost-filestore-aws-access-key-id
        version: latest
    - secretKey: secretkey
      remoteRef:
        key: mattermost-filestore-aws-secret-access-key
        version: latest
    - secretKey: bucketName
      remoteRef:
        key: mattermost-filestore-bucket-name
        version: latest
