apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-access-key
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aws-access-key