apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secret-access-key
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets
  target:
    name: aws-secret-access-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: value
      remoteRef:
        key: aws-secret-access-key
        version: latest
