apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: utro-customer-gateway-firebase-admin
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: utro-customer-gateway-firebase-admin
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: utro-customer-gateway-firebase-admin
        version: latest
