apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lethsencrypt-http-private-key
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: letsencrypt-http-private-key
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: letsencrypt-http-private-key
        version: latest