apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resend-staging
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: resend-staging
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: resend-staging
        version: latest
