apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-webhook-secret-resend
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: prod-webhook-secret-resend
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: prod-webhook-secret-resend
        version: latest
