apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resend-production
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: resend-production
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: resend-production
        version: latest
