apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stripe-prod-webhook-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: stripe-prod-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: stripe-prod-webhook-secret
        version: latest
