apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twilio-staging-phone
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
  target:
    name: twilio-staging-phone
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: twilio-staging-phone
        version: latest
