apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: n8n-user-password
   namespace: atlas-operator
spec:
   refreshInterval: 1h
   secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
   target:
    name: n8n-user-password
    creationPolicy: Owner
   data:
     - secretKey: password
       remoteRef:
         key: n8n-user-password
         version: latest
