apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: atlas-db-url
   namespace: atlas-operator
spec:
   refreshInterval: 1h
   secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
   target:
    name: atlas-db-url
    creationPolicy: Owner
   data:
     - secretKey: value
       remoteRef:
         key: atlas-db-url
         version: latest
