apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: atlas-operator
  namespace: flux-system
spec:
  url: oci://ghcr.io/ariga/charts
  type: oci
  interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: atlas-operator
  namespace: atlas-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: atlas-operator
      version: "0.7.10"  # Update as needed
      sourceRef:
        kind: HelmRepository
        name: atlas-operator
        namespace: flux-system
  install:
    createNamespace: true
  values:
    prewarmDevDB: false
