apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: n8n-user
  namespace: atlas-operator
spec:
  urlFrom:
    secretKeyRef:
      name: atlas-db-url
      key: value
  vars:
    - key: n8n_password
      valueFrom:
        secretKeyRef:
          name: n8n-user-password
          key: password
  users:
  - name: n8nuser
    password: '{{ .n8n_password }}'
    roles:
      - LOGIN
  schema:
    sql: |
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'n8nuser') THEN
          CREATE ROLE n8nuser WITH LOGIN PASSWORD '{{ .n8n_password }}';
        END IF;
      END $$;
      CREATE SCHEMA IF NOT EXISTS my_schema;
      CREATE TABLE IF NOT EXISTS my_schema.my_table (
          id SERIAL PRIMARY KEY
      );

      INSERT INTO my_schema.my_table DEFAULT VALUES;
      INSERT INTO my_schema.my_table DEFAULT VALUES;
      INSERT INTO my_schema.my_table DEFAULT VALUES;
      INSERT INTO my_schema.my_table DEFAULT VALUES;

