apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: n8n-user
  namespace: atlas-operator
spec:
  urlFrom:
    secretKeyRef:
      name: atlas-db-url
      key: value
  vars:
    - key: n8n_password
      valueFrom:
        secretKeyRef:
          name: n8n-user-password
          key: password
  schema:
    sql: |
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'n8nuser') THEN
          CREATE ROLE n8nuser WITH LOGIN PASSWORD '{{ .n8n_password }}';
        END IF;
      END $$;

      -- Just run create db — may fail if already exists (OK on idempotent runs)
      CREATE DATABASE n8n OWNER n8nuser;

      GRANT ALL PRIVILEGES ON DATABASE n8n TO n8nuser;
