apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault-operator
      version: 1.22.5
      sourceRef:
        kind: HelmRepository
        name: bank-vaults-oci
        namespace: flux-system
  install:
    createNamespace: true
  values: {}
