apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets
  target:
    name: tailscale-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: clientId
      remoteRef:
        key: tailscale-oauth-client-id
        version: latest
    - secretKey: clientSecret
      remoteRef:
        key: tailscale-oauth-client-secret
        version: latest
