apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.4.8" # Optional: pin to known stable version
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
  install:
    createNamespace: false
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true
