apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tempo-s3-credentials
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secrets
  target:
    name: tempo-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: tempo-s3-aws-access-key-id
        version: latest
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: tempo-s3-aws-secret-access-key
        version: latest
