apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
   name: n8n-secrets
   namespace: n8n
spec:
   refreshInterval: 1h
   secretStoreRef:
    name: google-secrets
    kind: ClusterSecretStore
   target:
    name: n8n-user-password
    creationPolicy: Owner
   data:
     - secretKey: N8N_ENCRYPTION_KEY
       remoteRef:
         key: n8n-user-password
         version: latest
     - secretKey: N8N_BASIC_AUTH_PASSWORD
       remoteRef:
         key: n8n-user-password
         version: latest
     - secretKey: DB_POSTGRESDB_PASSWORD
       remoteRef:
         key: n8n-user-password
         version: latest