apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: "3.10.0"  # or latest from the repo
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    engines:
      local:
        lvm:
          enabled: true
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    localpv-provisioner:
      rbac:
        create: true
    lvm-localpv:
      crds:
        csi:
          volumeSnapshots:
            enabled: true
        lvmLocalPv:
          enabled: true
    mayastor:
      crds:
        csi:
          volumeSnapshots:
            enabled: false
      csi:
        node:
          initContainers:
            enabled: false
      etcd:
        clusterDomain: "cluster.local"
      localpv-provisioner:
        enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: true
          keep: true
    zfs-localpv:
      crds:
        csi:
          volumeSnapshots:
            enabled: false
        zfsLocalPv:
          enabled: false
